services:
  postgres-restaurant:
    image: postgres:15
    container_name: postgres-restaurant
    environment:
      POSTGRES_DB: restaurant_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5431:5432"